import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "./components/Navbar"; 
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Ata Berk Yılmaz | Software Developer",
  description: "Generated by Ata Berk Yılmaz",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className={inter.className}>
        <Navbar />

        {/* Main Content */}
        <main className="flex-grow container mx-auto px-4 sm:px-6 lg:px-8">
          {children}
        </main>

        {/* Footer */}
        <footer className="text-gray-700 border-t border-gray-700 py-4 mt-4">
          <div className="container mx-auto text-center">
            <p>© {new Date().getFullYear()} Ata Berk Yılmaz. All rights reserved.</p>
          </div>
        </footer>
      </body>
    </html>
  );
}
